### ISSUE TITLE
Add method to search for data assets

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-codeocean-api#10]
Acceptance criteria:

- [ ] ~~`get_data_assets`~~
- [ ] a method called `search_data_assets`
- [ ] exposes all parameters of the data asset API
- [ ] ~if `start` and `limit` are passed, return the requested number of assets~
- [ ] ~if `start` and `limit` are not passed, return all matching assets (make multiple requests)~

Notes:
Returning all the data assets will be handled in #14

**Comment by dana-rocha** [comment]
- [ ] Create a separate method called `search_data_assets`

**Comment by dyf** [comment]
> * [ ]  Create a separate method called `search_data_assets`

Updated the acceptance criteria, thanks.

**Comment by jtyoung84** [comment]
> Acceptance criteria:
> 
> * [ ]  ~`get_data_assets`~
> * [ ]  a method called `search_data_assets`
> * [ ]  exposes all parameters of the data asset API
> * [ ]  if `start` and `limit` are passed, return the requested number of assets
> * [ ]  if `start` and `limit` are not passed, return all matching assets (make multiple requests)

^ @dyf I think we should use the default behavior provided by codeocean if start and limit are not passed

**Comment by dyf** [comment]
> > Acceptance criteria:
> > 
> > * [ ]   ~`get_data_assets`~
> > * [ ]   a method called `search_data_assets`
> > * [ ]   exposes all parameters of the data asset API
> > * [ ]   if `start` and `limit` are passed, return the requested number of assets
> > * [ ]   if `start` and `limit` are not passed, return all matching assets (make multiple requests)
> 
> ^ @dyf I think we should use the default behavior provided by codeocean if start and limit are not passed

We can make it a separate ticket if you want, but I this is functionality I would like.

**Comment by jtyoung84** [comment]
> > > Acceptance criteria:
> > > 
> > > * [ ]    ~`get_data_assets`~
> > > * [ ]    a method called `search_data_assets`
> > > * [ ]    exposes all parameters of the data asset API
> > > * [ ]    if `start` and `limit` are passed, return the requested number of assets
> > > * [ ]    if `start` and `limit` are not passed, return all matching assets (make multiple requests)
> > 
> > 
> > ^ @dyf I think we should use the default behavior provided by codeocean if start and limit are not passed
> 
> We can make it a separate ticket if you want, but this is functionality I would like.

I put this as a separate ticket.
