### ISSUE TITLE
Add utility method to return all data assets that match a query

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-codeocean-api#14]
# User story
As a user, I want to call a single method to return all data assets matching a query, so I don't have to call a method multiple times.

# Acceptance criteria
- [ ] There should be a method that makes multiple requests (if necessary) to the code ocean backend to retrieve all data assets using the search data asset api.

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
Should wait until #10 is finished first to make this easier

**Comment by dana-rocha** [comment]
- Add data into a temporary list and append the data to it
- Return the list as a response
