### ISSUE TITLE
API call to change permissions on data asset

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-codeocean-api#19]
# User story
As a user, I want an api to change permissions on a data asset, so I can avoid manually changing permissions in the ui.

# Acceptance criteria
- [x] There should be method in the python client called `update_permissions` that alters the permissions of a data asset.

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified
6. - [x] Ticket is prioritized and sized

# Notes
Can use the following examples:

```
#!/usr/bin/env bash

# curl -X POST \
# 'https://acmecorp-edge.codeocean.com/api/v1/data_assets/abc-123/permissions' \
# -u $API_KEY: -H 'Content-Type: application/json' \
# --data-raw '{
# 	"users": [ {"email": "test@codeocean.com", "role": "owner"} ] ,
# 	"groups": [ {"group": "ad-group", "role": "viewer"} ] ,
# 	"everyone": true
# }'

#role: owner or viewer
curl -X POST \
'https://acmecorp-edge.codeocean.com/api/v1/data_assets/abc-123/permissions' \
-u $API_KEY: -H 'Content-Type: application/json' \
--data-raw '{
	"users": [ {"email": "test@codeocean.com", "role": "owner"} ] ,
	"everyone": true
}'
```

**Comment by aricAI** [comment]
I have communicated with CodeOcean support and they say they do not have an endpoint for modifying permissions...

**Comment by aricAI** [comment]
Ok, should be good to go now

**Comment by aricAI** [comment]
make everyone optional
