### ISSUE TITLE
Explicitly close request connections

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-codeocean-api#23]
# User story
As a user, I want to ensure connections are being closed, so that resources are being used efficiently.

# Acceptance criteria
- [x] All the requests responses should be wrapped into a with statement

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified
6. - [x] Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by Louise-X10** [comment]
Each method request is already handled by context managers internally by the request module, as documented [here](https://github.com/psf/requests/blob/main/requests/api.py#L60).
