### ISSUE TITLE
Add method to move files to another bucket

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-codeocean-api#9]
This is primarily to enable us to move data from a private codeocean bucket to our open data bucket.

Acceptance Criteria:

- [ ] `move_data_asset`
- [ ] Moves data to a new bucket
- [ ] New prefix/path is the same as the name of the asset
- [ ] No assets are created or deleted in the process
- [ ] No provenance is lost on the data asset record
- [ ] Asset is marked as "external"

Note: it's possible this does not work with the existing API.

---

Code Ocean is building this feature, blocking for now

**Comment by jtyoung84** [comment]
CodeOcean is going to handle this on their end
